apiVersion: v1
kind: Service
metadata:
  name: ifra-docs-service
  namespace: production
  labels:
    app:  ifra-docs
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app:  ifra-docs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ifra-docs
  namespace: production
spec:
  selector:
    matchLabels:
      app:  ifra-docs
  replicas: 1
  template:
    metadata:
      labels:
        app:  ifra-docs
    spec:
      containers:
      - name:  ifra-docs
        image: ifrasoft/ifra-docs:2021